const PresentMemberProfiles = [
  {
    id: 0,
    firstname: "aaa",
    lastname: "sdfas",
    profile_pic_url: "https://picsum.photos/id/1005/200",
    get_year_display: "2nd Year",
    github: "2nd Year",
    facebook: "asdff",
    instagram: "asdfdf",
    linkedin: "asdfdf",
  },
  {
    id: 1,
    firstname: "bbb",
    lastname: "sdfas",
    profile_pic_url: "https://picsum.photos/id/1006/200",
    get_year_display: "2nd Year",
    github: "2nd Year",
    facebook: "asdff",
    instagram: "asdfdf",
    linkedin: "asdfdf",
  },
  {
    id: 2,
    firstname: "cccc",
    lastname: "sdfas",
    profile_pic_url: "https://picsum.photos/id/1011/200",
    get_year_display: "2nd Year",
    github: "2nd Year",
    facebook: "asdff",
    instagram: "asdfdf",
    linkedin: "asdfdf",
  },
  {
    id: 3,
    firstname: "ddd",
    lastname: "sdfas",
    profile_pic_url: "https://picsum.photos/id/1008/200",
    get_year_display: "2nd Year",
    github: "2nd Year",
    facebook: "asdff",
    instagram: "asdfdf",
    linkedin: "asdfdf",
  },
  {
    id: 4,
    firstname: "eee",
    lastname: "sdfas",
    profile_pic_url: "https://picsum.photos/id/1009/200",
    get_year_display: "2nd Year",
    github: "2nd Year",
    facebook: "asdff",
    instagram: "asdfdf",
    linkedin: "asdfdf",
  },
  {
    id: 5,
    firstname: "aaa",
    lastname: "sdfas",
    profile_pic_url: "https://picsum.photos/id/1005/200",
    get_year_display: "2nd Year",
    github: "2nd Year",
    facebook: "asdff",
    instagram: "asdfdf",
    linkedin: "asdfdf",
  },
  {
    id: 6,
    firstname: "bbb",
    lastname: "sdfas",
    profile_pic_url: "https://picsum.photos/id/1006/200",
    get_year_display: "2nd Year",
    github: "2nd Year",
    facebook: "asdff",
    instagram: "asdfdf",
    linkedin: "asdfdf",
  },
  {
    id: 7,
    firstname: "cccc",
    lastname: "sdfas",
    profile_pic_url: "https://picsum.photos/id/1011/200",
    get_year_display: "2nd Year",
    github: "2nd Year",
    facebook: "asdff",
    instagram: "asdfdf",
    linkedin: "asdfdf",
  },
  {
    id: 8,
    firstname: "ddd",
    lastname: "sdfas",
    profile_pic_url: "https://picsum.photos/id/1008/200",
    get_year_display: "2nd Year",
    github: "2nd Year",
    facebook: "asdff",
    instagram: "asdfdf",
    linkedin: "asdfdf",
  },
  {
    id: 9,
    firstname: "eee",
    lastname: "sdfas",
    profile_pic_url: "https://picsum.photos/id/1009/200",
    get_year_display: "2nd Year",
    github: "2nd Year",
    facebook: "asdff",
    instagram: "asdfdf",
    linkedin: "asdfdf",
  },
  {
    id: 10,
    firstname: "fff",
    lastname: "sdfas",
    profile_pic_url: "https://picsum.photos/id/1010/200",
    get_year_display: "2nd Year",
    github: "2nd Year",
    facebook: "asdff",
    instagram: "asdfdf",
    linkedin: "asdfdf",
  },
  {
    id: 11,
    firstname: "ggg",
    lastname: "sdfas",
    profile_pic_url: "https://picsum.photos/id/1011/200",
    get_year_display: "2nd Year",
    github: "2nd Year",
    facebook: "asdff",
    instagram: "asdfdf",
    linkedin: "asdfdf",
  },
  {
    id: 12,
    firstname: "aaa",
    lastname: "sdfas",
    profile_pic_url: "https://picsum.photos/id/1005/200",
    get_year_display: "2nd Year",
    github: "2nd Year",
    facebook: "asdff",
    instagram: "asdfdf",
    linkedin: "asdfdf",
  },
  {
    id: 13,
    firstname: "bbb",
    lastname: "sdfas",
    profile_pic_url: "https://picsum.photos/id/1006/200",
    get_year_display: "2nd Year",
    github: "2nd Year",
    facebook: "asdff",
    instagram: "asdfdf",
    linkedin: "asdfdf",
  },
  {
    id: 14,
    firstname: "cccc",
    lastname: "sdfas",
    profile_pic_url: "https://picsum.photos/id/1011/200",
    get_year_display: "2nd Year",
    github: "2nd Year",
    facebook: "asdff",
    instagram: "asdfdf",
    linkedin: "asdfdf",
  },
  {
    id: 15,
    firstname: "ddd",
    lastname: "sdfas",
    profile_pic_url: "https://picsum.photos/id/1008/200",
    get_year_display: "2nd Year",
    github: "2nd Year",
    facebook: "asdff",
    instagram: "asdfdf",
    linkedin: "asdfdf",
  },
  {
    id: 16,
    firstname: "eee",
    lastname: "sdfas",
    profile_pic_url: "https://picsum.photos/id/1009/200",
    get_year_display: "2nd Year",
    github: "2nd Year",
    facebook: "asdff",
    instagram: "asdfdf",
    linkedin: "asdfdf",
  },
];

export default PresentMemberProfiles;