const projects = [
  {
    id: 0,
    projectName: "aaa",
    shortDescription: "sdfas",
    projectImage: "https://picsum.photos/id/1005/200",
    //get_year_display: "2nd Year",
    repoLink: "2nd Year",
    longDescription: "asdff",
    team: "the team behind this project was mentored by ABC / This project is done by ABC",
    projectLink: "asdfdf",
    field: "Web Development",
  },
  {
    id: 1,
    projectName: "bbb",
    shortDescription: "sdfas",
    projectImage: "https://picsum.photos/id/1006/200",
    //get_year_display: "2nd Year",
    repoLink: "2nd Year",
    longDescription: "asdff",
    team: "the team behind this project was mentored by ABC / This project is done by ABC",
    projectLink: "asdfdf",
    field: "Machine Learning",
  },
  {
    id: 2,
    projectName: "cccc",
    shortDescription: "sdfas",
    projectImage: "https://picsum.photos/id/1011/200",
    //get_year_display: "2nd Year",
    repoLink: "2nd Year",
    longDescription: "asdff",
    team: "the team behind this project was mentored by ABC / This project is done by ABC",
    projectLink: "asdfdf",
    field: "Java",
  },
  {
    id: 3,
    projectName: "ddd",
    shortDescription: "sdfas",
    projectImage: "https://picsum.photos/id/1008/200",
    //get_year_display: "2nd Year",
    repoLink: "2nd Year",
    longDescription: "asdff",
    team: "the team behind this project was mentored by ABC / This project is done by ABC",
    projectLink: "asdfdf",
    field: "Android",
  },
  {
    id: 4,
    projectName: "eee",
    shortDescription: "sdfas",
    projectImage: "https://picsum.photos/id/1009/200",
    //get_year_display: "2nd Year",
    repoLink: "2nd Year",
    longDescription: "asdff",
    team: "the team behind this project was mentored by ABC / This project is done by ABC",
    projectLink: "asdfdf",
    field: "Python",
  },
  {
    id: 5,
    projectName: "aaa",
    shortDescription: "sdfas",
    projectImage: "https://picsum.photos/id/1005/200",
    //get_year_display: "2nd Year",
    repoLink: "2nd Year",
    longDescription: "asdff",
    team: "the team behind this project was mentored by ABC / This project is done by ABC",
    projectLink: "asdfdf",
    field: "Android",
  },
  {
    id: 6,
    projectName: "bbb",
    shortDescription: "sdfas",
    projectImage: "https://picsum.photos/id/1006/200",
    //get_year_display: "2nd Year",
    repoLink: "2nd Year",
    longDescription: "asdff",
    team: "the team behind this project was mentored by ABC / This project is done by ABC",
    projectLink: "asdfdf",
    field: "Web Development",
  },
  {
    id: 7,
    projectName: "cccc",
    shortDescription: "sdfas",
    projectImage: "https://picsum.photos/id/1011/200",
    //get_year_display: "2nd Year",
    repoLink: "2nd Year",
    longDescription: "asdff",
    team: "the team behind this project was mentored by ABC / This project is done by ABC",
    projectLink: "asdfdf",
    field: "Android",
  },
  {
    id: 8,
    projectName: "ddd",
    shortDescription: "sdfas",
    projectImage: "https://picsum.photos/id/1008/200",
    //get_year_display: "2nd Year",
    repoLink: "2nd Year",
    longDescription: "asdff",
    team: "the team behind this project was mentored by ABC / This project is done by ABC",
    projectLink: "asdfdf",
    field: "Web Development",
  },
  {
    id: 9,
    projectName: "eee",
    shortDescription: "sdfas",
    projectImage: "https://picsum.photos/id/1009/200",
    //get_year_display: "2nd Year",
    repoLink: "2nd Year",
    longDescription: "asdff",
    team: "the team behind this project was mentored by ABC / This project is done by ABC",
    projectLink: "asdfdf",
    field: "Machine Learning",
  },
  {
    id: 10,
    projectName: "fff",
    shortDescription: "sdfas",
    projectImage: "https://picsum.photos/id/1010/200",
    //get_year_display: "2nd Year",
    repoLink: "2nd Year",
    longDescription: "asdff",
    team: "the team behind this project was mentored by ABC / This project is done by ABC",
    projectLink: "asdfdf",
    field: "Android",
  },
  {
    id: 11,
    projectName: "ggg",
    shortDescription: "sdfas",
    projectImage: "https://picsum.photos/id/1011/200",
    //get_year_display: "2nd Year",
    repoLink: "2nd Year",
    longDescription: "asdff",
    team: "the team behind this project was mentored by ABC / This project is done by ABC",
    projectLink: "asdfdf",
    field: "Web Development",
  },
  {
    id: 12,
    projectName: "aaa",
    shortDescription: "sdfas",
    projectImage: "https://picsum.photos/id/1005/200",
    //get_year_display: "2nd Year",
    repoLink: "2nd Year",
    longDescription: "asdff",
    team: "the team behind this project was mentored by ABC / This project is done by ABC",
    projectLink: "asdfdf",
    field: "Android",
  },
  {
    id: 13,
    projectName: "bbb",
    shortDescription: "sdfas",
    projectImage: "https://picsum.photos/id/1006/200",
    //get_year_display: "2nd Year",
    repoLink: "2nd Year",
    longDescription: "asdff",
    team: "the team behind this project was mentored by ABC / This project is done by ABC",
    
    field: "Machine Learning",
  },
  {
    id: 14,
    projectName: "cccc",
    shortDescription: "sdfas",
    projectImage: "https://picsum.photos/id/1011/200",
    //get_year_display: "2nd Year",
    repoLink: "2nd Year",
    longDescription: "asdff",
    team: "the team behind this project was mentored by ABC / This project is done by ABC",
    projectLink: "asdfdf",
    field: "Android",
  },
  {
    id: 15,
    projectName: "ddd",
    shortDescription: "sdfas",
    projectImage: "https://picsum.photos/id/1008/200",
    //get_year_display: "2nd Year",
    repoLink: "2nd Year",
    longDescription: "asdff",
    team: "the team behind this project was mentored by ABC / This project is done by ABC",
    projectLink: "asdfdf",
    field: "Java",
  },
  {
    id: 16,
    projectName: "eee",
    shortDescription: "sdfas",
    projectImage: "https://picsum.photos/id/1009/200",
    //get_year_display: "2nd Year",
    repoLink: "2nd Year",
    longDescription: "asdff",
    team: "the team behind this project was mentored by ABC / This project is done by ABC",
    projectLink: "asdfdf",
    field: "Android",
  },
];

export default projects;
