const typographyOptions = (palette) => ({
	fontFamily: 'Satoshi',
	allVariants: {
		color: palette.text.primary,
		fontFamily: 'Satoshi'
	},
	fontWeightRegular: 400,
	fontWeightMedium: 600,
	fontWeightBold: 900,
	displayLarge: {
		fontFamily: 'Satoshi',
		fontSize: '57px',
		lineHeight: '64px',
		letterSpacing: '-0.25px',
		fontWeight: 900,
		color: palette.text.primary,
	},
	displayMedium: {
		fontFamily: 'Satoshi',
		fontSize: '45px',
		lineHeight: '52px',
		letterSpacing: '0px',
		fontWeight: 900,
		color: palette.text.primary,
	},
	displaySmall: {
		fontFamily: 'Satoshi',
		fontSize: '36px',
		lineHeight: '44px',
		letterSpacing: '0px',
		fontWeight: 900,
		color: palette.text.primary,
	},

	headlineLarge: {
		fontFamily: 'Satoshi',
		fontSize: '32px',
		lineHeight: '40px',
		letterSpacing: '0px',
		fontWeight: 700,
		color: palette.text.primary,
	},
	headlineMedium: {
		fontFamily: 'Satoshi',
		fontSize: '28px',
		lineHeight: '36px',
		letterSpacing: '0px',
		fontWeight: 700,
		color: palette.text.primary,
	},
	headlineSmall: {
		fontFamily: 'Satoshi',
		fontSize: '24px',
		lineHeight: '32px',
		letterSpacing: '0px',
		fontWeight: 700,
		color: palette.text.primary,
	},

	titleLarge: {
		fontFamily: 'Satoshi',
		fontSize: '22px',
		lineHeight: '28px',
		letterSpacing: '0px',
		fontWeight: 400,
		color: palette.text.primary,
	},
	titleMedium: {
		fontFamily: 'Satoshi',
		fontSize: '16px',
		lineHeight: '24px',
		letterSpacing: '0.15px',
		fontWeight: 600,
		color: palette.text.primary,
	},
	titleSmall: {
		fontFamily: 'Satoshi',
		fontSize: '14px',
		lineHeight: '20px',
		letterSpacing: '0.1px',
		fontWeight: 600,
		color: palette.text.primary,
	},

	labelLarge: {
		fontFamily: 'Satoshi',
		fontSize: '14px',
		lineHeight: '20px',
		letterSpacing: '0.1px',
		fontWeight: 600,
		color: palette.text.primary,
	},
	labelMedium: {
		fontFamily: 'Satoshi',
		fontSize: '12px',
		lineHeight: '16px',
		letterSpacing: '0.5px',
		fontWeight: 600,
		color: palette.text.primary,
	},
	labelSmall: {
		fontFamily: 'Satoshi',
		fontSize: '11px',
		lineHeight: '16px',
		letterSpacing: '0.5px',
		fontWeight: 600,
		color: palette.text.primary,
	},

	bodyLarge: {
		fontFamily: 'Satoshi',
		fontSize: '16px',
		lineHeight: '24px',
		letterSpacing: '0.5px',
		fontWeight: 400,
		color: palette.text.secondary,
	},
	bodyMedium: {
		fontFamily: 'Satoshi',
		fontSize: '14px',
		lineHeight: '20px',
		letterSpacing: '0.25px',
		fontWeight: 400,
		color: palette.text.secondary,
	},
	bodySmall: {
		fontFamily: 'Satoshi',
		fontSize: '12px',
		lineHeight: '16px',
		letterSpacing: '0px',
		fontWeight: 400,
		color: palette.text.secondary,
	},
	button: {
		fontFamily: 'Satoshi',
		fontSize: '14px',
		lineHeight: '20px',
		letterSpacing: '0.1px',
		fontWeight: 600,
		color: palette.text.primary,
	}
})

export default typographyOptions