name: Build and deploy

on:
  push:
    branches: [ main ]
    
  # Run workflow manually
  workflow_dispatch:
  
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: CI=false npm install && CI=false npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ENIGMA_DEV_WEB }}'
          channelId: live
          projectId: enigma-dev-web
